const panels=document.querySelectorAll(".panel");function showPanel(id){panels.forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active")}
const drawer=document.getElementById("drawer");const drawerMask=document.getElementById("drawerMask");const openDrawer=document.getElementById("hamburger");const linkDraw=document.getElementById("navDraw");const linkCollage=document.getElementById("navCollage");const linkInfo=document.getElementById("navInfo");openDrawer.addEventListener("click",()=>{drawer.classList.add("open")});drawerMask.addEventListener("click",()=>{drawer.classList.remove("open")});linkDraw.addEventListener("click",()=>{drawer.classList.remove("open");showPanel("view-draw")});linkCollage.addEventListener("click",()=>{drawer.classList.remove("open");showPanel("view-collage")});linkInfo.addEventListener("click",()=>{drawer.classList.remove("open");showPanel("view-info")});
const fortuneTitle=document.getElementById("fortuneTitle");const fortuneGrade=document.getElementById("fortuneGrade");const fortuneText=document.getElementById("fortuneText");const fortuneCard=document.getElementById("fortuneCard");const tube=document.querySelector(".lottery-tube");const sticks=document.querySelector(".sticks");const tapHint=document.getElementById("tapHint");const btnRetry=document.getElementById("btnRetry");const btnAccept=document.getElementById("btnAccept");
const terms=[{key:"春分",month:3,day:20},{key:"清明",month:4,day:4}];const fortunes={"春分":[{grade:"上上签",text:"日夜均分，万物向新"},{grade:"大吉",text:"春光正好，宜出发行"},{grade:"中吉",text:"平衡自得，心境安宁"},{grade:"小吉",text:"播种今日，收获不远"}],"清明":[{grade:"上上签",text:"清风拂柳，心愿可期"},{grade:"大吉",text:"踏青问春，好事相随"},{grade:"中吉",text:"且念先人，行止得当"},{grade:"小吉",text:"雨润大地，静待花开"}]};function currentTerm(){const d=new Date();const y=d.getFullYear();const m=d.getMonth()+1;const ds=terms.filter(t=>t.month===m).map(t=>({name:t.key,date:new Date(y,t.month-1,t.day)})).sort((a,b)=>a.date-b.date);if(ds.length===0)return"春分";let n=ds[0].name;if(ds.length===2&&d>=ds[1].date)n=ds[1].name;return n}
function randomFortune(){const t=currentTerm();const pool=fortunes[t]||fortunes["春分"];return pool[Math.floor(Math.random()*pool.length)]}
function playShakeThenDraw(){tapHint.classList.add("hide");sticks.classList.add("shake-once");tube.classList.add("shake-once");setTimeout(()=>{sticks.classList.remove("shake-once");tube.classList.remove("shake-once");drawFortune()},1000)}
function drawFortune(){const f=randomFortune();fortuneTitle.textContent=currentTerm();fortuneGrade.textContent=f.grade;fortuneText.textContent=f.text;fortuneCard.classList.remove("show");fortuneCard.style.zIndex="5";void fortuneCard.offsetWidth;fortuneCard.classList.add("show");showActions()}
document.getElementById("lotteryArea").addEventListener("click",playShakeThenDraw);btnRetry.addEventListener("click",()=>{fortuneCard.classList.remove("show");setTimeout(playShakeThenDraw,50)});btnAccept.addEventListener("click",()=>{showPanel("view-collage")});
if(window.DeviceMotionEvent){let last=0;window.addEventListener("devicemotion",e=>{const a=e.accelerationIncludingGravity;if(!a)return;const mag=Math.abs(a.x)+Math.abs(a.y)+Math.abs(a.z);const now=Date.now();if(mag>30&&now-last>1500){last=now;playShakeThenDraw()}},false)}
const canvas=document.getElementById("collageCanvas");const ctx=canvas.getContext("2d");const stickerLayer=document.getElementById("stickerLayer");const limitTip=document.getElementById("limitTip");const btnBg=document.getElementById("btnBg");const btnStickerNature=document.getElementById("btnStickerNature");const btnStickerXiaSun=document.getElementById("btnStickerXiaSun");const btnStickerLayout=document.getElementById("btnStickerLayout");const btnSave=document.getElementById("btnSave");const btnClear=document.getElementById("btnClear");const btnToggleMode=document.getElementById("btnToggleMode");const bgModal=document.getElementById("bgModal");const bgGrid=document.getElementById("bgGrid");const bgClose=document.getElementById("bgClose");const stickerModal=document.getElementById("stickerModal");const stickerGrid=document.getElementById("stickerGrid");const modalTitle=document.getElementById("modalTitle");const modalClose=document.getElementById("modalClose");const drawActions=document.getElementById("drawActions");const previewWrap=document.querySelector(".preview-wrap");const collageLayout=document.querySelector(".collage-layout");const sideMenu=document.querySelector(".side-menu");
const backgrounds=["./assets/backgrounds/bg1.svg","./assets/backgrounds/bg2.svg","./assets/backgrounds/bg3.svg","./assets/backgrounds/bg4.svg"];const stickers={风物:["./assets/stickers/sun.svg","./assets/stickers/cloud.svg","./assets/stickers/rain.svg","./assets/stickers/leaf.svg","./assets/stickers/flower.svg"],小笋:["./assets/stickers/bamboo.svg","./assets/stickers/cat.svg","./assets/stickers/book.svg","./assets/stickers/hat.svg"],排版:["./assets/stickers/text-good.svg","./assets/stickers/text-bless.svg","./assets/stickers/text-peace.svg"]};let state={bg:null,items:[],mode:"edit"};
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);if(state.bg){const img=new Image();img.src=state.bg;img.onload=()=>{ctx.drawImage(img,0,0,canvas.width,canvas.height)}}}
function fitCanvas(){const wrap=document.querySelector(".preview-wrap");const w=wrap.clientWidth-16;const r=1000/750;canvas.width=w;canvas.height=w*r;render()}
window.addEventListener("resize",fitCanvas);fitCanvas();
function setActiveButton(btn){[btnBg,btnStickerNature,btnStickerXiaSun,btnStickerLayout,btnClear,btnToggleMode,btnSave].forEach(b=>b.classList.remove("active"));btn.classList.add("active")}
function sizePicker(card, anchorBtn){const w=previewWrap.clientWidth;const h=Math.max(260,Math.min(previewWrap.clientHeight-40, Math.round(previewWrap.clientHeight*0.72)));const btnTop=anchorBtn.getBoundingClientRect().top;const containerTop=collageLayout.getBoundingClientRect().top;card.style.width=w+"px";card.style.height=h+"px";card.style.top=(btnTop-containerTop)+"px"}
function openBg(){setActiveButton(btnBg);sizePicker(bgModal,btnBg);bgModal.classList.remove("hidden");bgModal.classList.add("show");bgGrid.innerHTML="";backgrounds.forEach(src=>{const img=document.createElement("img");img.src=src;img.addEventListener("click",()=>{state.bg=src;bgModal.classList.remove("show");bgModal.classList.add("hidden");render()});bgGrid.appendChild(img)})}
btnBg.addEventListener("click",openBg);bgClose.addEventListener("click",()=>{bgModal.classList.remove("show");bgModal.classList.add("hidden")});
function updateStickerControls(){const disabled=state.items.length>=5;const msg="贴纸超过5个，不能再加了";btnStickerNature.classList.toggle("disabled",disabled);btnStickerXiaSun.classList.toggle("disabled",disabled);btnStickerLayout.classList.toggle("disabled",disabled);if(disabled){limitTip.textContent=msg;limitTip.style.display="block";setTimeout(()=>{limitTip.style.display="none"},1800)}}
function openSticker(cat){if(state.items.length>=5){updateStickerControls();return}const anchor=cat==="风物"?btnStickerNature:cat==="小笋"?btnStickerXiaSun:btnStickerLayout;setActiveButton(anchor);sizePicker(stickerModal,anchor);stickerModal.classList.remove("hidden");stickerModal.classList.add("show");modalTitle.textContent=cat+"贴纸";stickerGrid.innerHTML="";stickers[cat].forEach(src=>{const img=document.createElement("img");img.src=src;img.addEventListener("click",()=>{addSticker(src);stickerModal.classList.remove("show");stickerModal.classList.add("hidden")});stickerGrid.appendChild(img)})}
btnStickerNature.addEventListener("click",()=>openSticker("风物"));btnStickerXiaSun.addEventListener("click",()=>openSticker("小笋"));btnStickerLayout.addEventListener("click",()=>openSticker("排版"));modalClose.addEventListener("click",()=>{stickerModal.classList.remove("show");stickerModal.classList.add("hidden")});
function addSticker(src){const el=document.createElement("img");el.src=src;el.className="sticker";el.style.width="120px";const rect=stickerLayer.getBoundingClientRect();const cx=rect.width/2;const cy=rect.height/2;const jitterX=(Math.random()-0.5)*rect.width*0.1;const jitterY=(Math.random()-0.5)*rect.height*0.1;const item={el,src,x:cx+jitterX,y:cy+jitterY,scale:1,rot:0,lastTap:0,dragging:false};stickerLayer.appendChild(el);state.items.push(item);gesture(item);updateStickerControls()}
function gesture(item){let touches=[];function sel(s){state.items.forEach(i=>i.el.classList.remove("selected"));if(s)item.el.classList.add("selected")}function apply(){item.el.style.transform=`translate(${item.x}px,${item.y}px) rotate(${item.rot}rad) scale(${item.scale}) translate(-50%,-50%)`}function ensureRemove(){if(!item.el.querySelector(".remove")){const rm=document.createElement("button");rm.textContent="×";rm.className="remove";rm.addEventListener("click",()=>{stickerLayer.removeChild(item.el);state.items=state.items.filter(i=>i!==item);updateStickerControls()});item.el.appendChild(rm)}}function toggleRemove(){ensureRemove();item.el.classList.toggle("show-remove")}
function startTouch(e){e.preventDefault();if(state.mode==="delete"){stickerLayer.removeChild(item.el);state.items=state.items.filter(i=>i!==item);updateStickerControls();return}sel(true);touches=[...e.touches];item.dragging=true}
function moveTouch(e){e.preventDefault();const ts=[...e.touches];if(touches.length===1&&ts.length===1){const dx=ts[0].clientX-touches[0].clientX;const dy=ts[0].clientY-touches[0].clientY;item.x+=dx;item.y+=dy;touches=ts;apply()}else if(touches.length>=2&&ts.length>=2){const d0=Math.hypot(touches[0].clientX-touches[1].clientX,touches[0].clientY-touches[1].clientY);const d1=Math.hypot(ts[0].clientX-ts[1].clientX,ts[0].clientY-ts[1].clientY);const s=d1/d0;item.scale=Math.max(0.3,Math.min(3,item.scale*s));const a0=Math.atan2(touches[0].clientY-touches[1].clientY,touches[0].clientX-touches[1].clientX);const a1=Math.atan2(ts[0].clientY-ts[1].clientY,ts[0].clientX-ts[1].clientX);item.rot+=a1-a0;touches=ts;apply()}}
function outOfBounds(){const rect=stickerLayer.getBoundingClientRect();return item.x<0||item.y<0||item.x>rect.width||item.y>rect.height}
function endTouch(e){const now=Date.now();if(now-item.lastTap<300){toggleRemove()}item.lastTap=now;touches=[...e.touches];if(touches.length===0){item.dragging=false;sel(false);if(outOfBounds()){stickerLayer.removeChild(item.el);state.items=state.items.filter(i=>i!==item);updateStickerControls()}}}
function startMouse(e){e.preventDefault();if(state.mode==="delete"){stickerLayer.removeChild(item.el);state.items=state.items.filter(i=>i!==item);updateStickerControls();return}sel(true);item.dragging=true;item._mx=e.clientX;item._my=e.clientY}
function moveMouse(e){if(!item.dragging)return;const dx=e.clientX-item._mx;const dy=e.clientY-item._my;item.x+=dx;item.y+=dy;item._mx=e.clientX;item._my=e.clientY;apply()}
function endMouse(){item.dragging=false;sel(false);if(outOfBounds()){stickerLayer.removeChild(item.el);state.items=state.items.filter(i=>i!==item);updateStickerControls()}}
item.el.addEventListener("touchstart",startTouch,{passive:false});item.el.addEventListener("touchmove",moveTouch,{passive:false});item.el.addEventListener("touchend",endTouch,{passive:false});item.el.addEventListener("mousedown",startMouse);document.addEventListener("mousemove",moveMouse);document.addEventListener("mouseup",endMouse);apply()}
btnClear.addEventListener("click",()=>{state.items.forEach(i=>i.el.remove());state.items=[];render();updateStickerControls()});
function saveImage(){const BASE_W=750,BASE_H=1000;const off=document.createElement("canvas");off.width=BASE_W;off.height=BASE_H;const octx=off.getContext("2d");function drawBg(next){if(state.bg){const bg=new Image();bg.src=state.bg;bg.onload=()=>{octx.drawImage(bg,0,0,BASE_W,BASE_H);next()}}else next()}function drawStickers(){let pending=state.items.length;if(pending===0)return finish();const rect=stickerLayer.getBoundingClientRect();const sx=BASE_W/rect.width;const sy=BASE_H/rect.height;state.items.forEach(i=>{const img=new Image();img.src=i.src;img.onload=()=>{octx.save();const cx=i.x*sx;const cy=i.y*sy;octx.translate(cx,cy);octx.rotate(i.rot);octx.scale(i.scale,i.scale);const w=120*sx;const h=120*sy;octx.drawImage(img,-w/2,-h/2,w,h);octx.restore();pending--;if(pending===0)finish()}})}function finish(){const url=off.toDataURL("image/png");const a=document.createElement("a");a.href=url;a.download="jieqi.png";document.body.appendChild(a);a.click();a.remove()}drawBg(drawStickers)}
btnSave.addEventListener("click",saveImage);
function showActions(){drawActions.classList.add("show")}
btnToggleMode.addEventListener("click",()=>{state.mode=state.mode==="edit"?"delete":"edit";btnToggleMode.textContent=state.mode==="delete"?"编辑模式":"删除模式";const tip=document.getElementById("modeTip");if(state.mode==="delete"){tip.textContent="点击可删除贴纸";tip.style.display="block";setTimeout(()=>{tip.style.display="none"},1000)}else{tip.style.display="none"}});
